%
% Routes:
%  route(from, to, company).

route(krk, waw, plllot).
route(krk, muc, plllot).
route(krk, tlv, plllot).

route(waw, krk, plllot).
route(waw, lhr, plllot).
route(waw, cdg, plllot).
route(waw, jfk, plllot).
route(waw, yyz, plllot).

route(lhr, waw, plllot).

route(cdg, waw, plllot).

route(muc, fco, lufthansa).

route(fco, muc, lufthansa).

route(tlv, waw, plllot).

route(jfk, waw, pllot).

route(yyz, waw, pllot).

route(yyz, yul, aircanada).

route(yul, yyz, aircanada).